spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/million_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&severTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 9606
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080